services:
  - type: web
    name: taska-core-me
    env: go
    plan: free
    region: ohio
    buildCommand: go build -o main ./cmd/api
    startCommand: ./main
    autoDeploy: true
    envVars:
      - key: GO_ENVIRONMENT
        value: production
      - key: JWT_SECRET
        value: your-256-bit-secret
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PORT
        value: 5432
