name: CI Checks

on:
  pull_request:
    branches: [develop, release/*, master]

env:
  GOPRIVATE: github.com/taskalataminfo2026/*
  GONOSUMDB: github.com/taskalataminfo2026/*
  GONOPROXY: github.com/taskalataminfo2026/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN_PRIVATE }} # Usa el token tambiÃ©n para el checkout

      - name: Configure Git for private modules
        run: |
          echo "machine github.com login ${{ secrets.TOKEN_PRIVATE }}" > ~/.netrc
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git config --global url."https://github.com/".insteadOf "ssh://git@github.com/"
          git config --global url."https://${{ secrets.TOKEN_PRIVATE }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Verify dependencies
        run: go mod tidy

      ## Si tienes linter, lo puedes activar luego
      ## - name: Run Linter
      ##   run: go vet ./...

      - name: Run Tests
        run: go test ./... -v